### ISSUE TITLE
Error: EOF occurred in violation of protocol (_ssl.c:661)

### ISSUE THREAD

**Issue by compyy** [CheckPoint-APIs-Team/ExportImportPolicyPackage#1]
Why Do we get these errors, its random not specific to any host or network while importing.

Failed to import host with name [HOEXPR_195.85.246.24]. Error: EOF occurred in violation of protocol (_ssl.c:661)

**Comment by CheckPoint-APIs-Team** [comment]
Which version of python are you running on the machine?

**Comment by compyy** [comment]
its Ubuntu 16.04 running python 2.7.13

**Comment by CheckPoint-APIs-Team** [comment]
Try using python version 2.7.9.
It should work without problems.

**Comment by compyy** [comment]
I ran the script directly from SMS, it worked without errors.

**Comment by CheckPoint-APIs-Team** [comment]
Strange. Maybe a connection issue from Ubuntu to SMS, maybe a certificate.
We open a https connection to the server.

**Comment by compyy** [comment]
any how you can close the ticket, for me issue is resolved, I am just waiting for Manual NAT to be included as well, my migration is waiting for the update.

**Comment by CheckPoint-APIs-Team** [comment]
Manual NAT will be included soon.
I'll post a notification here.

**Comment by CheckPoint-APIs-Team** [comment]
Added a support for manual NAT rules.
Enjoy!
