### ISSUE TITLE
Enhancement request - resolve object names to addresses

### ISSUE THREAD

**Issue by pgastinger** [CheckPoint-APIs-Team/ExportImportPolicyPackage#10]
Your (NAT) export basically works pretty good, but I have an enhancement request:

At the moment, an exported json nat rule looks like that:

```
    {
        "__before_auto_rules": false,
        "original-destination": "MY_PUBLIC_NET",
        "install-on.0": "Policy Targets",
        "comments": "",
        "translated-source": "Original",
        "method": "static",
        "translated-destination": "WEBServer_1",
        "original-source": "Any",
        "translated-service": "Original",
        "enabled": true,
        "original-service": "Any",
        "position": 273
    },
```
It would be nice if you would resolve objects (for the access rule export as well) to their ip-addresses/networks, e.g.:

```
    {
        "__before_auto_rules": false,
        "original-destination.0": "2xx.xx.xx.xx/24",
        "original-destination.1": "2yy.yy.yy.yy/24",
        "install-on.0": "Policy Targets",
        "comments": "",
        "translated-source": "Original",
        "method": "static",
        "translated-destination.0": "10.x.x.x.1",
        "original-source": "Any",
        "translated-service": "Original",
        "enabled": true,
        "original-service": "Any",
        "position": 273
    },
```

In the export files, I have all the files to resolve these objects by myself, but in some cases, it would be nice to have an exported rule base with addresses (Hosts and Nets) instead of the object names. 

A cli option for that would be great. Thanks.

**Comment by CheckPoint-APIs-Team** [comment]
Hi,
The exported NAT data is formatted for use later by import process. It is used as a **paylod** for NAT rules creation during import. This data is **strictly** formatted.
Any additional data NOT related to valid payload data will fail the import process.
Therefore, we cannot implement your suggested enhancement...
