### ISSUE TITLE
"error_message": "APIResponse received a response which is not a valid JSON.

### ISSUE THREAD

**Issue by dexield** [CheckPoint-APIs-Team/ExportImportPolicyPackage#2]
Why do I get this error>

Login to management server failed. lib::APIResponse
{
    "data": null,
    "error_message": "APIResponse received a response which is not a valid JSON.
",
    "res_obj": {},
    "status_code": 403,
    "success": false
}

**Comment by CheckPoint-APIs-Team** [comment]
Hi,
It seems that the login command failed and returned NULL value.
Please go to your management server and cd to "$FWDIR/log" folder, and upload here a file named "api.elg", so we can check what happened.
Thanks.

**Comment by CheckPoint-APIs-Team** [comment]
no response recieved...
