### ISSUE TITLE
API hang

### ISSUE THREAD

**Issue by incubenet** [CheckPoint-APIs-Team/ExportImportPolicyPackage#4]
Dear API team,

We have another issue.
API was hang when a group object containing many objects(around 2000) is included in the rule.
There are about 12 such rules.

![api response](https://user-images.githubusercontent.com/35084285/34701701-f9a9c4dc-f52c-11e7-8e90-fabdac8b5707.png)

**Comment by CheckPoint-APIs-Team** [comment]
Let's try to increase the timeout of our Apache Web server:
1. on the management server got to folder "/web/conf/"
2. edit the file httpd2.conf - change the line "Timeout 300" to "Timeout 1800" (it is in seconds)
3. save the file
4. run command "api reconf"
5. run the export/import tool again.
Please let me know if this helps.

**Comment by incubenet** [comment]
Dear API team,

 

Thank you, I will try it.

 

Regards,
