### ISSUE TITLE
When the rule is imported, the error occurs in middle.

### ISSUE THREAD

**Issue by incubenet** [CheckPoint-APIs-Team/ExportImportPolicyPackage#5]
Dear API Team,

I downloaded latest package file.
When the rule is imported, the error occurs in middle.
So, the rule is not imported.
This error did not occur before.

Following message:
Failed to publish import of access-rules from tar file #3! Access-rules from said file were not imported!. Error: Publish failed because of validation errors

I attach the import.export.log

Regards,

[import_export.log](https://github.com/CheckPoint-APIs-Team/ExportImportPolicyPackage/files/1617964/import_export.log)

**Comment by CheckPoint-APIs-Team** [comment]
Hi,
It seems that you are re-importing the same package to the same management server.
There are many errors in the attached log file that show this.
Is this correct?

**Comment by incubenet** [comment]
Dear API Team,

 

Yes, the many object have been already created.

But, the policy package is not exists.

 

We can ignore “Failed to import ~ “.

 

But, please look this error.

“Failed to publish import of access-rules from tar file #3! Access-rules from said file were not imported!. Error: Publish failed because of validation errors”

 

Regards,

**Comment by CheckPoint-APIs-Team** [comment]
Ok, let's do the following to check why publish fails:
Run "api status <file-name>" command on the management server and it will generate a **tar file** with <file-name> in the middle in current directory.
Please attach the file here for investigation.
Thanks.

**Comment by incubenet** [comment]
I upload the tar.file


[2018.01.10_18-28-05_api_data_error.zip](https://github.com/CheckPoint-APIs-Team/ExportImportPolicyPackage/files/1618226/2018.01.10_18-28-05_api_data_error.zip)

**Comment by CheckPoint-APIs-Team** [comment]
Hi,
Found the problem.
You are using an object "VNC" in a services column of one of your access rules in layer "CB-DB-150827 Security".
It is an "Applications" object and in order to use it in services column, you should have a flag enabled on your layer settings ("Applications & URL Filtering").
Anyway, I'll fix the code to have it enabled always...
I'll inform you when I upload the fix.

**Comment by CheckPoint-APIs-Team** [comment]
Updated the source code with a fix.
Please download the new source and retry.
Thanks.

**Comment by CheckPoint-APIs-Team** [comment]
Hi, have you tried the new source code?
Does it fix the problem?

**Comment by incubenet** [comment]
I will try and update.

**Comment by incubenet** [comment]
Resolved
