### ISSUE TITLE
What is import error message?

### ISSUE THREAD

**Issue by incubenet** [CheckPoint-APIs-Team/ExportImportPolicyPackage#9]
Failed to import access-rule with name [ICO-20170201-530]. Error: EOF occurred in violation of protocol (_ssl.c:661)

**Comment by CheckPoint-APIs-Team** [comment]
This is HTTPS/SSL Connection issue.
Where are you running the tool - on the management server or on remote machine?
If on remote machine, which version of python is installed? Which OS?
Thanks.

**Comment by CheckPoint-APIs-Team** [comment]
BTW, this is the same error as reported in another issue (#1).

**Comment by incubenet** [comment]
Remote machine : python 2.7.14  and Windows 7

**Comment by CheckPoint-APIs-Team** [comment]
This configuration should work. There were SSL issues for python version **below** 2.7.9.
The error is not related to the tool directly. It is a connection issue. If the problem remains, install python version 2.7.9.
